#Ask the user for at least ten questions
#Read in each answer and store it in a variable
#Print out the result

print("Welcome to Mad Libs!")
print("Give me a name: ")
name=input()
print("Give me a number")
num1 = float(input())
print(type(num1))
print("Give me a colour")
colour=input()
print("Give me a vehicle")
vehicle=input()
print("Give me a Present participle verb")
Presentparticipleverb=input()
print("Give me a person")
person=input()
print("Give me a second colour")
colour2=input()
print("Give me a place")
place=input()
print("Give me a job")
job=input()
print("Give me a shape")
shape=input()
print("One day",name,"saw",num1,"Clowns getting out of their",colour,vehicle,Presentparticipleverb,"along the way to the clown convention, ",name,"ends up following the clowns and sees",person,"screaming at a manager of mcdonald's for making their chicken nuggets",colour2,', the manager ends up going ballistic and dashes to a',place,", backflip kicks a",job,"and falls down a",shape,"manhole when they leave the",place,",",name,"ends up going home due to their crazy day.")
